// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransportService.DataAccess;

#nullable disable

namespace AdhiSreeTransportService.Migrations
{
    [DbContext(typeof(TransportServiceDBContext))]
    [Migration("20260205045951_partymodelmodified")]
    partial class partymodelmodified
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("District", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StateId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("ID");

                    b.HasIndex("StateId");

                    b.ToTable("District");
                });

            modelBuilder.Entity("State", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("State");
                });

            modelBuilder.Entity("TransportService.Model.DestinationGroup", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("ID"));

                    b.Property<long?>("DestinationGroupId")
                        .HasColumnType("bigint");

                    b.Property<short>("DestinationId")
                        .HasColumnType("smallint");

                    b.Property<long>("TransportId")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("DestinationGroupId");

                    b.HasIndex("DestinationId");

                    b.ToTable("DestinationGroups");
                });

            modelBuilder.Entity("TransportService.Model.Driver", b =>
                {
                    b.Property<short>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<short>("ID"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("AdharNo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LicenceNo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Mobile1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Mobile2")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Driver");
                });

            modelBuilder.Entity("TransportService.Model.Location", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DistrictId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.HasIndex("DistrictId");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("TransportService.Model.Party", b =>
                {
                    b.Property<short>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<short>("ID"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("GstNo")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("OfficePhone")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Pincode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Party");
                });

            modelBuilder.Entity("TransportService.Model.TransportEntry", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("ID"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<decimal>("CloseKM")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("DestinationGroupId")
                        .HasColumnType("bigint");

                    b.Property<short>("DriverId")
                        .HasColumnType("smallint");

                    b.Property<int>("From")
                        .HasColumnType("int");

                    b.Property<short>("HaltDays")
                        .HasColumnType("smallint");

                    b.Property<decimal>("Loading")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("LoadingCommision")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Narration")
                        .HasColumnType("longtext");

                    b.Property<string>("Other")
                        .HasColumnType("longtext");

                    b.Property<short>("Party1")
                        .HasColumnType("smallint");

                    b.Property<decimal>("Rent")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ReturnDestinationId")
                        .HasColumnType("int");

                    b.Property<decimal>("StartKM")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("To")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Unloading")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("UnloadingCommision")
                        .HasColumnType("decimal(65,30)");

                    b.Property<short>("VehicleId")
                        .HasColumnType("smallint");

                    b.Property<short>("VehicleTypeId")
                        .HasColumnType("smallint");

                    b.HasKey("ID");

                    b.HasIndex("DriverId");

                    b.HasIndex("From");

                    b.HasIndex("Party1");

                    b.HasIndex("ReturnDestinationId");

                    b.HasIndex("To");

                    b.HasIndex("VehicleId");

                    b.HasIndex("VehicleTypeId");

                    b.ToTable("TransportEntry");
                });

            modelBuilder.Entity("TransportService.Model.Vehicle", b =>
                {
                    b.Property<short>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<short>("ID"));

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Registration")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<short>("TypeId")
                        .HasColumnType("smallint");

                    b.HasKey("ID");

                    b.HasIndex("TypeId");

                    b.ToTable("Vehicle");
                });

            modelBuilder.Entity("TransportService.Model.VehicleType", b =>
                {
                    b.Property<short>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<short>("ID"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("VehicleType");
                });

            modelBuilder.Entity("District", b =>
                {
                    b.HasOne("State", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("TransportService.Model.DestinationGroup", b =>
                {
                    b.HasOne("TransportService.Model.TransportEntry", null)
                        .WithMany("DestinationGroups")
                        .HasForeignKey("DestinationGroupId");

                    b.HasOne("TransportService.Model.Party", "Party")
                        .WithMany()
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Party");
                });

            modelBuilder.Entity("TransportService.Model.Location", b =>
                {
                    b.HasOne("District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("TransportService.Model.TransportEntry", b =>
                {
                    b.HasOne("TransportService.Model.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TransportService.Model.Location", "LocationFrom")
                        .WithMany()
                        .HasForeignKey("From")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TransportService.Model.Party", "Party_Party1")
                        .WithMany()
                        .HasForeignKey("Party1")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TransportService.Model.Location", "ReturnDestination")
                        .WithMany()
                        .HasForeignKey("ReturnDestinationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TransportService.Model.Location", "LocationTo")
                        .WithMany()
                        .HasForeignKey("To")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TransportService.Model.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TransportService.Model.VehicleType", "VehicleType")
                        .WithMany()
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("LocationFrom");

                    b.Navigation("LocationTo");

                    b.Navigation("Party_Party1");

                    b.Navigation("ReturnDestination");

                    b.Navigation("Vehicle");

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("TransportService.Model.Vehicle", b =>
                {
                    b.HasOne("TransportService.Model.VehicleType", "VehicleType")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("TransportService.Model.TransportEntry", b =>
                {
                    b.Navigation("DestinationGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
